### ISSUE TITLE
能否支持LocalDate和LocalDateTime

### ISSUE THREAD

**Issue by herowzz** [jsonzou/jmockdata#12]
实体bean里添加LocalDate和LocalDateTime属性，生成mock报错：java.lang.InstantiationException

具体在BeanMocker里第30行
`Object result = clazz.newInstance();`
LocalDate是无法newInstance的

**Comment by herowzz** [comment]
自定义扩展配置也不行
```
public class LocalDateMock implements Mocker<Object> {
	@Override
	public LocalDate mock(MockConfig mockConfig) {
		return LocalDate.now();
	}
}
```

```
MockConfig config = new MockConfig();
config.registerMocker(new LocalDateMock(), LocalDate.class);
BasicBean basicBean = JMockData.mock(BasicBean.class);
```

还是抛出异常
```
Exception in thread "main" com.github.jsonzou.jmockdata.MockException: com.github.jsonzou.jmockdata.MockException: java.lang.InstantiationException: java.time.LocalDate
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:45)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:37)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.JMockData.mock(JMockData.java:32)
	at com.github.jsonzou.jmockdata.JMockData.mock(JMockData.java:21)
	at com.wzz.test.TestProject.mock.TestMockData.main(TestMockData.java:16)
Caused by: com.github.jsonzou.jmockdata.MockException: java.lang.InstantiationException: java.time.LocalDate
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:45)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:37)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:40)
	... 5 more
Caused by: java.lang.InstantiationException: java.time.LocalDate
	at java.lang.Class.newInstance(Class.java:427)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:30)
	... 8 more
Caused by: java.lang.NoSuchMethodException: java.time.LocalDate.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 9 more
```

**Comment by jsonzoup** [comment]
> 
> 
> 自定义扩展可以解决
> 
> ```
> public class LocalDateMock implements Mocker<Object> {
> 	@Override
> 	public LocalDate mock(MockConfig mockConfig) {
> 		return LocalDate.now();
> 	}
> }
> ```
> 
> ```
> MockConfig config = new MockConfig();
> config.registerMocker(new LocalDateMock(), LocalDate.class);
> BasicBean basicBean = JMockData.mock(BasicBean.class, config);
> ```
> 
> 生成数据正常
你好，是可以通过这种方式解决的哈。
后续升级上去排除某些类型的模拟。
@huayanYu

**Comment by jsonzoup** [comment]
新版本已支持
https://github.com/jsonzou/jmockdata/releases/tag/jmockdata-4.2.0-RELEASE
