### ISSUE TITLE
timestamp报错

### ISSUE THREAD

**Issue by geeaks** [jsonzou/jmockdata#34]
Caused by: com.github.jsonzou.jmockdata.MockException: com.github.jsonzou.jmockdata.MockException: java.lang.InstantiationException: java.sql.Timestamp
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:63)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:38)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:57)
	... 130 common frames omitted
Caused by: com.github.jsonzou.jmockdata.MockException: java.lang.InstantiationException: java.sql.Timestamp
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:63)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:38)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:57)
	... 133 common frames omitted
Caused by: java.lang.InstantiationException: java.sql.Timestamp
	at java.lang.Class.newInstance(Class.java:427)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:35)
	... 136 common frames omitted
Caused by: java.lang.NoSuchMethodException: java.sql.Timestamp.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 137 common frames omitted

**Comment by jsonzoup** [comment]
你好，当前原生不支持类型 java.sql.Timestamp.
但是框架可以支持扩展新的类型。请参考wiki.

**Comment by jsonzoup** [comment]
自定义Mocker类注册

MockConfig mockConfig = new MockConfig()
            .registerMocker(Mocker mocker, Class<T>... clazzs)

**Comment by geeaks** [comment]
好的 多谢

**Comment by jsonzoup** [comment]
新版本已支持
https://github.com/jsonzou/jmockdata/releases/tag/jmockdata-4.2.0-RELEASE
