### ISSUE TITLE
建议增加对static字段mock的相关配置项

### ISSUE THREAD

**Issue by CZ-chen** [jsonzou/jmockdata#40]
在很多时候，我们不希望mock静态字段的值，因此，建议增加对static字段mock的相关配置项

**Comment by 6671246** [comment]
当bean中有静态类时mock会出现问题
Caused by: java.lang.IllegalAccessException: Can not set static final long field com.xxx.serialVersionUID to java.lang.Long
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at sun.reflect.UnsafeQualifiedStaticLongFieldAccessorImpl.set(UnsafeQualifiedStaticLongFieldAccessorImpl.java:77)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.github.jsonzou.jmockdata.util.ReflectionUtils.setFieldValue(ReflectionUtils.java:42)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.setFieldValueByFieldAccessible(BeanMocker.java:67)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:41)
	... 5 more

**Comment by jsonzoup** [comment]
4.3已支持
