### ISSUE TITLE
mock希望能针对静态属性进行过滤，或添加配置设置是否启用

### ISSUE THREAD

**Issue by 6671246** [jsonzou/jmockdata#46]
Caused by: java.lang.IllegalAccessException: Can not set static final long field com.aaa.serialVersionUID to java.lang.Long
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at sun.reflect.UnsafeQualifiedStaticLongFieldAccessorImpl.set(UnsafeQualifiedStaticLongFieldAccessorImpl.java:77)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.github.jsonzou.jmockdata.util.ReflectionUtils.setFieldValue(ReflectionUtils.java:42)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.setFieldValueByFieldAccessible(BeanMocker.java:67)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:41)
	... 5 more

**Comment by lysilver** [comment]
MockConfig mockConfig = new MockConfig()
                .globalConfig()
                .excludes("serialVersionUID");
JMockData.mock(*.class, mockConfig);

**Comment by jsonzoup** [comment]
4.3已支持排除final
