### ISSUE TITLE
当bean的某个字段类型为com.alibaba.fastjson.JSONObject时，mock这个bean会抛数组越界异常

### ISSUE THREAD

**Issue by h496022202** [jsonzou/jmockdata#58]
com.github.jsonzou.jmockdata.MockException: java.lang.ArrayIndexOutOfBoundsException: 0

	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:47)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:38)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.JMockData.mock(JMockData.java:33)

**Comment by h496022202** [comment]
if (this.clazz.isArray()) {
            mocker = new ArrayMocker(this.clazz);
        } else if (Map.class.isAssignableFrom(this.clazz)) {
            mocker = new MapMocker(this.genericTypes);
        } else if (Collection.class.isAssignableFrom(this.clazz)) {
            mocker = new CollectionMocker(this.clazz, this.genericTypes[0]);
        } else if (this.clazz.isEnum()) {
            mocker = new EnumMocker(this.clazz);
        } else {
            mocker = mockConfig.globalConfig().getMocker(this.clazz);
            if (mocker == null) {
                mocker = new BeanMocker(this.clazz);
            }
        }
源码中，走到这里JSONObject类型会被认为为MapMocker，然后再走MapMocker时候，会报数组越界。
本来在前面写了个拦截器：
MockConfig mockConfig = new MockConfig().
                registerBeanMockerInterceptor(JSONObject.class, (aClass, field, o, dataConfig) -> InterceptType.UNMOCK);
但是在setFieldValueByFieldAccessible方法中取拦截器
```
BeanMockerInterceptor bi = mockConfig.globalConfig().getBeanMockerInterceptor(this.clazz);
为什么这里传的是this.clazz，而不是field.type，这里拦截的只能是最终mock的类型，而不是需要拦截的class
```

**Comment by jsonzoup** [comment]
排除模拟可以用这个方法：
  .globalConfig()
            // 排除所有包含list/set/map字符的字段。表达式不区分大小写。
            .excludes("*List*","*Set*","*Map*")

或者你为JSONObject自定义一个而模拟器
自定义Mocker类注册

MockConfig mockConfig = new MockConfig()
            .registerMocker(Mocker mocker, Class<T>... clazzs)

**Comment by h496022202** [comment]
> 排除模拟可以用这个方法：
> .globalConfig()
> // 排除所有包含list/set/map字符的字段。表达式不区分大小写。
> .excludes("_List_","_Set_","_Map_")
> 
> 或者你为JSONObject自定义一个而模拟器
> 自定义Mocker类注册
> 
> MockConfig mockConfig = new MockConfig()
> .registerMocker(Mocker mocker, Class... clazzs)

我试过自定义模拟器
```
class JSONObjectMock implements Mocker {
    @Override
    public Object mock(DataConfig dataConfig) {
        return null;
    }
}
```
在使用的时候，这个走不到自定义mocker那里，就会被当做MapMocker拦截掉，导致报错：
测试代码：
```
@Test
    public void test_a(){
        MockConfig mockConfig = new MockConfig();
        mockConfig.registerMocker(new JSONObjectMock(), JSONObject.class);
        JMockData.mock(CommonActivityEntity.class,mockConfig);
    }
```
得到报错：
```
com.github.jsonzou.jmockdata.MockException: java.lang.ArrayIndexOutOfBoundsException: 0

	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:47)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:38)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.JMockData.mock(JMockData.java:33)
	at com.hupan.lakers.activity.impl.testJson.test_a(testJson.java:30)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.github.jsonzou.jmockdata.mocker.MapMocker.mock(MapMocker.java:26)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:38)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.setFieldValueByFieldAccessible(BeanMocker.java:67)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:44)
	... 4 more
```
并且，我尝试去写一个拦截器，去拦截JSONObject.class
```
MockConfig mockConfig = new MockConfig().
                    registerBeanMockerInterceptor(JSONObject.class, (aClass, field, o, dataConfig) -> InterceptType.UNMOCK);
JMockData.mock(CommonActivityEntity.class,mockConfig);
```
依然会得到上面的错误信息，跟踪代码发现：BeanMocker.java:64  ：BeanMockerInterceptor bi = mockConfig.globalConfig().getBeanMockerInterceptor(this.clazz);
这里传的class类型，应该是field的type，而不应该是这个参数所在类的类型
我试着改为:BeanMockerInterceptor bi = mockConfig.globalConfig().getBeanMockerInterceptor(field.getType()); 并放在maven中重新运行，就能够正常拦截到。
麻烦确认一下，谢谢

**Comment by doushichao** [comment]
我也遇到了这个问题，麻烦问一下这个由解决方案么？谢谢🙏
