### ISSUE TITLE
我的 Pojo 中的一个字段使用了 com.alibaba.fastjson.JSONObject 在 mock 的时候会抛数组越界异常 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by doushichao** [jsonzou/jmockdata#62]
```
Exception in thread "main" com.github.jsonzou.jmockdata.MockException: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:47)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:38)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.JMockData.mock(JMockData.java:33)
```

我使用了如下的拦截器都是不生效的

```java
mockConfig.registerBeanMockerInterceptor(JSONObject.class, (aClass, field, o, dataConfig) -> InterceptType.UNMOCK);
```

```java
public class JSONObjectMock implements Mocker<JSONObject> {
    @Override
    public JSONObject mock(DataConfig dataConfig) {
        return new JSONObject();
    }
}

mockConfig.registerMocker(new JSONObjectMock(), JSONObject.class);
```

**Comment by pprain** [comment]
遇到了同样的问题

**Comment by eye-gu** [comment]
可以改一下ClassMocker里面的先后顺序，从config中获取放前面
