### ISSUE TITLE
java.sql.Timestamp是否支持

### ISSUE THREAD

**Issue by fujialong** [jsonzou/jmockdata#7]
Caused by: com.github.jsonzou.jmockdata.MockException: java.lang.InstantiationException: java.sql.Timestamp
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:43)
	at com.github.jsonzou.jmockdata.mocker.ClassMocker.mock(ClassMocker.java:36)
	at com.github.jsonzou.jmockdata.mocker.BaseMocker.mock(BaseMocker.java:35)
	at com.github.jsonzou.jmockdata.mocker.BeanMocker.mock(BeanMocker.java:37)
	... 41 more

**Comment by jsonzoup** [comment]
目前还不支持。但是可以支持扩展配置。

MockConfig mockConfig = new MockConfig().registerMocker(mocker, java.sql.Timestamp.class)
其中 moker 可以参考DateMocker实现：

/**
 * Date对象模拟器
 */
public class DateMocker extends AbstractDateMock implements Mocker<Date> {

  public DateMocker(String startTimePattern, String endTime) {
    super(startTimePattern, endTime);
  }

  @Override
  public Date mock(MockConfig mockConfig) {
    return new Date(RandomUtils.nextLong(startTime, endTime));
  }

}

**Comment by jsonzoup** [comment]
后续可以增加支持此类型上去。

**Comment by jsonzoup** [comment]
新版本已支持
https://github.com/jsonzou/jmockdata/releases/tag/jmockdata-4.2.0-RELEASE
